/* Templated Mills-ratio kernels.  Ported from the original Cython prototype
 * (src/mathpf/mills.pyx, history in MathPF git); see mills.h for the API.
 *
 * Coefficients (C_Rrel, C_R1, C_R3, XCF_R*, N_FRAC_*, NSEG_*, TMAX_*, U_MAX,
 * X_NEG_MAX, M_SQRT2PI, M_SQRT2PI_2) are sourced from _mills_coef.h, which is
 * auto-generated by tools/cheby_fit.py.
 *
 * Phase-2 float instantiation re-uses the double coefficient tables, narrowed
 * at each Horner step.  Bit-equality with the original Cython code is enforced
 * by tests/test_pyref_consistency.py.
 */
#include "mills.h"
#include "_mills_coef.h"

#include <cmath>
#include <limits>

namespace mathpf
{
    using std::exp;

    /* ----------------------------------------------------------------------
     * MillsRatioRel_below1(x) = (sqrt(pi/2) - R(x))/x on [0, 1].  12 uniform
     * segments of degree 7 in C_Rrel; same per-call cost as MillsRatioDeriv1.
     * The two other [0, 1] consumers (MillsRatio, MillsRatioDeriv1) inline the
     * same lookup+Horner pattern, then apply their respective identities:
     *     R   = sqrt(pi/2) - x * Rrel
     *     R1  = 1 - x * R = 1 - x*(sqrt(pi/2) - x*Rrel)
     * ---------------------------------------------------------------------- */
    template<typename T>
    T MillsRatioRel_below1(T x)
    {
        int i = static_cast<int>(T(NSEG_RREL) * x);
        if (i >= NSEG_RREL) i = NSEG_RREL - 1;
        const T s = T(NSEG_RREL) * x - T(i);
        const int o = i * 8;
        const double* c = C_Rrel;
        return (((((((T(c[o+7]))*s + T(c[o+6]))*s + T(c[o+5]))*s + T(c[o+4]))*s + T(c[o+3]))*s + T(c[o+2]))*s + T(c[o+1]))*s + T(c[o]);
    }

    /* ----------------------------------------------------------------------
     * MillsRatio_CF(x_or_u, n, d) -- shared CF convergent for R / -R' / -R'''.
     *
     * Parameter x_or_u is interpreted polymorphically by d:
     *     d = 0:  x_or_u = x          -> R^[n](x)     = N/(x D)        (Mills ratio)
     *     d = 1:  x_or_u = x*x + 3    -> -R'^[n](x)   = Delta/D        (R1^[n])
     *     d = 3:  x_or_u = x*x + 3    -> -R'''^[n](x) = Gamma/D        (R3^[n])
     *
     * Delta(u) (deg n/2-1) and Gamma(u) (deg n/2-2) are evaluated by Horner in
     * the shifted variable u = x^2 + 3; then D = u*Delta - Gamma and N = D - Delta.
     * Total cost: (n-2) mults + 1 div.  The `if (d == 0)` branches are compile-
     * time constants at every call site (every caller passes a literal d).
     * ---------------------------------------------------------------------- */
    template<typename T>
    T MillsRatio_CF(T x_or_u, int n, int d)
    {
        T u, delta, gamma, D;
        if (d == 0)
            u = x_or_u * x_or_u + T(3.0);                  /* arg is x; form u inside */
        else
            u = x_or_u;                                     /* arg is already u = x^2 + 3 */

        if (n == 2) {                                       /* Delta=1, Gamma=0 (degenerate); D = u, N = u-1 */
            if (d == 0) return (u - T(1.0)) / (x_or_u * u); /* arg is x */
            if (d == 1) return T(1.0) / u;
            return T(0.0);                                  /* -R'''^[2] vanishes */
        }
        if (n == 4) {
            delta = T(4.0) + u;
            gamma = T(6.0);
        } else if (n == 6) {
            delta = T(12.0) + u * (T(12.0) + u);
            gamma = T(48.0) + u * T(6.0);
        } else if (n == 8) {
            delta = T(-24.0) + u * (T(114.0) + u * (T(24.0) + u));
            gamma = T(324.0) + u * (T(120.0) + u * T(6.0));
        } else if (n == 10) {
            delta = T(-1248.0) + u * (T(936.0) + u * (T(426.0) + u * (T(40.0) + u)));
            gamma = T(1728.0) + u * (T(1812.0) + u * (T(216.0) + u * T(6.0)));
        } else { /* n == 12 */
            delta = T(-22320.0) + u * (T(4932.0) + u * (T(6816.0) + u * (T(1116.0) + u * (T(60.0) + u))));
            gamma = T(-1080.0) + u * (T(24768.0) + u * (T(5472.0) + u * (T(336.0) + u * T(6.0))));
        }
        D = u * delta - gamma;                              /* = (x^2+3)*Delta - Gamma */
        if (d == 1) return delta / D;                       /* -R'^[n] = Delta/D */
        if (d == 3) return gamma / D;                       /* -R'''^[n] = Gamma/D */
        return (D - delta) / (x_or_u * D);                  /* d == 0: R^[n] = N/(xD), arg is x */
    }

    /* ----------------------------------------------------------------------
     * MillsRatio(x) = R(x); any sign.  Saturates to +inf for x < X_NEG_MAX.
     * ---------------------------------------------------------------------- */
    template<typename T>
    T MillsRatio(T x)
    {
        T s, d;
        int i, o;
        const double* c;
        if (x < T(0.0)) {
            if (x < T(X_NEG_MAX))                           /* exp(x^2/2) overflow -> saturate */
                return std::numeric_limits<T>::infinity();
            return T(M_SQRT2PI) * exp(T(0.5) * x * x) - MillsRatio(-x);
        }
        if (x <= T(1.0)) {
            i = static_cast<int>(T(NSEG_RREL) * x);
            if (i >= NSEG_RREL) i = NSEG_RREL - 1;
            s = T(NSEG_RREL) * x - T(i);
            o = i * 8;
            c = C_Rrel;
            const T rrel = (((((((T(c[o+7]))*s + T(c[o+6]))*s + T(c[o+5]))*s + T(c[o+4]))*s + T(c[o+3]))*s + T(c[o+2]))*s + T(c[o+1]))*s + T(c[o]);
            return T(M_SQRT2PI_2) - x * rrel;
        }
        if (x >= T(XCF_R[0])) {                             /* tiered CF via shared MillsRatio_CF */
            if (x >= T(XCF_R[6])) return T(1.0) / x;                          /* x >= 67000000: n=0 degenerate */
            if (x >= T(XCF_R[5])) return MillsRatio_CF(x, NCF_R[5], 0);       /* x in [548, 67e6):    CF n=2  */
            if (x >= T(XCF_R[4])) return MillsRatio_CF(x, NCF_R[4], 0);       /* x in [59.3, 548):    CF n=4  */
            if (x >= T(XCF_R[3])) return MillsRatio_CF(x, NCF_R[3], 0);       /* x in [24.1, 59.3):   CF n=6  */
            if (x >= T(XCF_R[2])) return MillsRatio_CF(x, NCF_R[2], 0);       /* x in [15.1, 24.1):   CF n=8  */
            if (x >= T(XCF_R[1])) return MillsRatio_CF(x, NCF_R[1], 0);       /* x in [11.4, 15.1):   CF n=10 */
            return                       MillsRatio_CF(x, NCF_R[0], 0);       /* x in [9.5, 11.4):    CF n=12 bridge */
        }
        d = T(N_FRAC_R1) + x;
        i = static_cast<int>(T(NSEG_R1) * (x - T(1.0)) / d);
        if (i >= TMAX_R1) i = TMAX_R1 - 1;
        s = (T(NSEG_R1 - i) * x - T(NSEG_R1 + i * N_FRAC_R1)) / d;
        o = i * 8;
        c = C_R1;
        return (T(1.0) - ((((((((T(c[o + 7]))*s + T(c[o + 6]))*s + T(c[o + 5]))*s + T(c[o + 4]))*s + T(c[o + 3]))*s + T(c[o + 2]))*s + T(c[o + 1]))*s + T(c[o]))) / x;
    }

    /* ----------------------------------------------------------------------
     * MillsRatioDeriv1(x) = -R'(x) = 1 - x R(x); any sign.
     * ---------------------------------------------------------------------- */
    template<typename T>
    T MillsRatioDeriv1(T x)
    {
        T s, d, u;
        int i, o;
        const double* c;
        if (x < T(0.0)) {
            if (x < T(X_NEG_MAX))
                return std::numeric_limits<T>::infinity();
            return T(M_SQRT2PI) * (-x) * exp(T(0.5) * x * x) + MillsRatioDeriv1(-x);
        }
        if (x <= T(1.0)) {
            i = static_cast<int>(T(NSEG_RREL) * x);
            if (i >= NSEG_RREL) i = NSEG_RREL - 1;
            s = T(NSEG_RREL) * x - T(i);
            o = i * 8;
            c = C_Rrel;
            const T rrel = (((((((T(c[o+7]))*s + T(c[o+6]))*s + T(c[o+5]))*s + T(c[o+4]))*s + T(c[o+3]))*s + T(c[o+2]))*s + T(c[o+1]))*s + T(c[o]);
            return T(1.0) - x * (T(M_SQRT2PI_2) - x * rrel);
        }
        if (x >= T(XCF_R1[0])) {
            u = x * x + T(3.0);                             /* shared with U_MAX guard and MillsRatio_CF */
            if (u > T(U_MAX)) return T(0.0);                /* +3 shift invisible at the saturation threshold */
            if (x >= T(XCF_R1[5])) return MillsRatio_CF(u, NCF_R1[5], 1);     /* x >= 12800:          CF n=2  */
            if (x >= T(XCF_R1[4])) return MillsRatio_CF(u, NCF_R1[4], 1);     /* x in [165, 12800):   CF n=4  */
            if (x >= T(XCF_R1[3])) return MillsRatio_CF(u, NCF_R1[3], 1);     /* x in [41, 165):      CF n=6  */
            if (x >= T(XCF_R1[2])) return MillsRatio_CF(u, NCF_R1[2], 1);     /* x in [21.2, 41):     CF n=8  */
            if (x >= T(XCF_R1[1])) return MillsRatio_CF(u, NCF_R1[1], 1);     /* x in [14.5, 21.2):   CF n=10 */
            return                        MillsRatio_CF(u, NCF_R1[0], 1);     /* x in [11.5, 14.5):   CF n=12 bridge */
        }
        d = T(N_FRAC_R1) + x;
        i = static_cast<int>(T(NSEG_R1) * (x - T(1.0)) / d);
        if (i >= TMAX_R1) i = TMAX_R1 - 1;
        s = (T(NSEG_R1 - i) * x - T(NSEG_R1 + i * N_FRAC_R1)) / d;
        o = i * 8;
        c = C_R1;
        return (((((((T(c[o + 7]))*s + T(c[o + 6]))*s + T(c[o + 5]))*s + T(c[o + 4]))*s + T(c[o + 3]))*s + T(c[o + 2]))*s + T(c[o + 1]))*s + T(c[o]);
    }

    /* ----------------------------------------------------------------------
     * MillsRatioDeriv3(x) = -R'''(x); any sign.
     * ---------------------------------------------------------------------- */
    template<typename T>
    T MillsRatioDeriv3(T x)
    {
        T s, d, u;
        int i, o;
        const double* c;
        if (x < T(0.0)) {
            if (x < T(X_NEG_MAX))
                return std::numeric_limits<T>::infinity();
            return T(M_SQRT2PI) * (-x) * (x * x + T(3.0)) * exp(T(0.5) * x * x) + MillsRatioDeriv3(-x);
        }
        if (x >= T(XCF_R3[0])) {
            u = x * x + T(3.0);
            if (u > T(U_MAX)) return T(0.0);
            if (x >= T(XCF_R3[4])) return MillsRatio_CF(u, NCF_R3[4], 3);     /* x >= 17300:          CF n=4  */
            if (x >= T(XCF_R3[3])) return MillsRatio_CF(u, NCF_R3[3], 3);     /* x in [210, 17300):   CF n=6  */
            if (x >= T(XCF_R3[2])) return MillsRatio_CF(u, NCF_R3[2], 3);     /* x in [50.5, 210):    CF n=8  */
            if (x >= T(XCF_R3[1])) return MillsRatio_CF(u, NCF_R3[1], 3);     /* x in [25.4, 50.5):   CF n=10 */
            return                        MillsRatio_CF(u, NCF_R3[0], 3);     /* x in [17.1, 25.4):   CF n=12 bridge */
        }
        d = T(N_FRAC_R3) + x;
        i = static_cast<int>(x / d * T(NSEG_R3));
        s = (T(NSEG_R3 - i) * x - T(i * N_FRAC_R3)) / d;
        o = i * 9;
        c = C_R3;
        return ((((((((T(c[o + 8]))*s + T(c[o + 7]))*s + T(c[o + 6]))*s + T(c[o + 5]))*s + T(c[o + 4]))*s + T(c[o + 3]))*s + T(c[o + 2]))*s + T(c[o + 1]))*s + T(c[o]);
    }

    /* ----------------------------------------------------------------------
     * Explicit float / double instantiations.  These export the symbols that
     * extern "C" shims (below) and other C++ TUs (qna pricer) reference.
     * ---------------------------------------------------------------------- */
    template double MillsRatio<double>(double);
    template float  MillsRatio<float>(float);
    template double MillsRatioDeriv1<double>(double);
    template float  MillsRatioDeriv1<float>(float);
    template double MillsRatioDeriv3<double>(double);
    template float  MillsRatioDeriv3<float>(float);
    template double MillsRatioRel_below1<double>(double);
    template float  MillsRatioRel_below1<float>(float);
    template double MillsRatio_CF<double>(double, int, int);
    template float  MillsRatio_CF<float>(float, int, int);

}  /* namespace mathpf */


/* --------------------------------------------------------------------------
 * extern "C" shims -- stable C ABI for the Cython binding and any other-
 * language FFI.  Double-only by design; forward to the mathpf::<double>
 * instantiations.  Single-line trampolines; the C++ compiler inlines them.
 *
 * NOTE: no DLLIXP here.  This source file is compiled directly into each
 * consuming Python extension (mathpf.mills, mathpf.mills_dd), so the
 * shims are same-module references with default linkage.  When the file is
 * vendored into a qna DLL build that wants cross-DLL access, the qna build
 * system can add `__declspec(dllexport)` via a wrapper header.
 * -------------------------------------------------------------------------- */
extern "C" {

double mathpf_MillsRatio(double x)              { return mathpf::MillsRatio<double>(x); }
double mathpf_MillsRatioDeriv1(double x)        { return mathpf::MillsRatioDeriv1<double>(x); }
double mathpf_MillsRatioDeriv3(double x)        { return mathpf::MillsRatioDeriv3<double>(x); }
double mathpf_MillsRatioRel_below1(double x)    { return mathpf::MillsRatioRel_below1<double>(x); }
double mathpf_MillsRatio_CF(double xu, int n, int d) { return mathpf::MillsRatio_CF<double>(xu, n, d); }

}  /* extern "C" */
