/* Mills-ratio kernels: R(x) = N(-x)/n(x), -R'(x), -R'''(x), and the
 * cancellation-free polynomial primitive (sqrt(pi/2) - R(x))/x on [0,1].
 *
 * Canonical math source for MathPF (Python distribution) and for vendoring into
 * the quants-net-analytics C++ pricer.  Templated on T in {float, double} so the
 * pricer can use either precision; the extern "C" surface below is double-only
 * (matches MathPF's Python binding, which exposes only doubles by design).
 *
 * Coefficient data lives in the sibling _mills_coef.h (auto-generated by
 * tools/cheby_fit.py).  Vendoring this file into qna also requires CommonMacro.h
 * and _mills_coef.h to land in the same directory.
 *
 * NOTE on DLL exports.  This header intentionally does NOT mark the declarations
 * with DLLIXP.  In MathPF's wheel build, mills.cpp is compiled directly into each
 * consuming Python extension -- there are no DLL boundaries to cross.  When the
 * file is vendored into a qna build that wants cross-DLL access, qna can wrap
 * these declarations in a thin DLLIXP-decorated header in its own tree.
 */
#ifndef MATHPF_KERNELS_MILLS_H
#define MATHPF_KERNELS_MILLS_H

#include "CommonMacro.h"  /* QNSPACE alias; DLLIXP macro available if qna re-wraps */

QNSPACE
{
    /* Templated declarations.  Float instantiations narrow from the double
     * coefficient tables at the use site; a Phase-4 follow-up will add
     * dedicated float-tuned coefficient tables and a true float specialisation. */
    template<typename T> T MillsRatio(T x);                 /* R(x), any sign       */
    template<typename T> T MillsRatioDeriv1(T x);           /* -R'(x) = 1 - x R(x)  */
    template<typename T> T MillsRatioDeriv3(T x);           /* -R'''(x)             */
    template<typename T> T MillsRatioRel_below1(T x);       /* (sqrt(pi/2)-R(x))/x  */
    template<typename T> T MillsRatio_CF(T x_or_u, int n, int d);  /* shared CF kernel */
}

#ifdef __cplusplus
extern "C" {
#endif

/* Stable C ABI for Cython / ctypes / other-language bindings.  Double-only. */
double mathpf_MillsRatio(double x);
double mathpf_MillsRatioDeriv1(double x);
double mathpf_MillsRatioDeriv3(double x);
double mathpf_MillsRatioRel_below1(double x);
double mathpf_MillsRatio_CF(double x_or_u, int n, int d);

#ifdef __cplusplus
}
#endif

#endif
