/* Mills-ratio kernels: R(x) = N(-x)/n(x), -R'(x), -R'''(x), and the
 * cancellation-free polynomial primitive (sqrt(pi/2) - R(x))/x on [0,1].
 *
 * Canonical math source for MathPF (Python distribution) and for vendoring
 * into downstream pricer libraries.  Templated on T in {float, double} so
 * vendoring consumers can use either precision; the extern "C" surface below
 * is double-only (matches MathPF's Python binding, which exposes only doubles
 * by design).
 *
 * Templates live in `namespace mathpf` (MathPF owns its own namespace; the
 * `mathpf_*` C symbols are the language-neutral ABI).  Consumers vendor the
 * `_kernels/` tree as-is and either qualify with `mathpf::` or pull names in
 * with `using namespace mathpf;` inside their own namespace blocks.
 *
 * Coefficient data lives in the sibling _mills_coef.h (auto-generated by
 * tools/cheby_fit.py).  Vendoring this file into another tree requires
 * _mills_coef.h to land in the same directory.
 */
#ifndef MATHPF_KERNELS_MILLS_H
#define MATHPF_KERNELS_MILLS_H

namespace mathpf
{
    /* Templated declarations.  Float instantiations narrow from the double
     * coefficient tables at the use site; a Phase-4 follow-up will add
     * dedicated float-tuned coefficient tables and a true float specialisation. */
    template<typename T> T MillsRatio(T x);                 /* R(x), any sign       */
    template<typename T> T MillsRatioDeriv1(T x);           /* -R'(x) = 1 - x R(x)  */
    template<typename T> T MillsRatioDeriv3(T x);           /* -R'''(x)             */
    template<typename T> T MillsRatioRel_below1(T x);       /* (sqrt(pi/2)-R(x))/x  */
    template<typename T> T MillsRatio_CF(T x_or_u, int n, int d);  /* shared CF kernel */
}

#ifdef __cplusplus
extern "C" {
#endif

/* Stable C ABI for Cython / ctypes / other-language bindings.  Double-only. */
double mathpf_MillsRatio(double x);
double mathpf_MillsRatioDeriv1(double x);
double mathpf_MillsRatioDeriv3(double x);
double mathpf_MillsRatioRel_below1(double x);
double mathpf_MillsRatio_CF(double x_or_u, int n, int d);

#ifdef __cplusplus
}
#endif

#endif
