"""Generate high-precision reference values for the Mills primitives R, R1,
R3, R_rel at x = 0, 0.5, 1.0, ..., 20.0 (m = 0..40, x = 0.5 m) using mpmath
at 50 decimal digits, then emit a Python module containing the values as
plain float constants for the test suite to import.

The generated file (tests/_ref_table.py) is committed; mpmath is NOT a
test-time dependency.  Re-run this generator only when extending the
anchor grid or revising precision.

Usage:
    python tools/gen_mills_ref.py            # prints to stdout
    python tools/gen_mills_ref.py --write    # overwrites tests/_ref_table.py
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import mpmath as mp


# 50 decimal digits is comfortably more than double precision (~17 digits)
# minus headroom for any cancellation inside the formulas below.
mp.mp.dps = 50


def R(x):
    """Mills ratio R(x) = N(-x)/n(x) = sqrt(pi/2) exp(x^2/2) erfc(x/sqrt(2)).
    Computed with the erfc-scaling identity for numerical stability."""
    xm = mp.mpf(x)
    return mp.sqrt(mp.pi / 2) * mp.exp(xm * xm / 2) * mp.erfc(xm / mp.sqrt(2))


def R1(x):
    """R1(x) = -R'(x) = 1 - x R(x)."""
    xm = mp.mpf(x)
    return 1 - xm * R(xm)


def R3(x):
    """R3(x) = -R'''(x) = (x^2 + 3) R1(x) - 1
    Equivalent to (x^2 + 3)(1 - x R) - 1."""
    xm = mp.mpf(x)
    return (xm * xm + 3) * R1(xm) - 1


def R_rel(x):
    """Cancellation-free near-zero form on [0, 1]:
        R_rel(x) = (sqrt(pi/2) - R(x)) / x ,
        R_rel(0) := 1   (by L'Hopital: R(x) = sqrt(pi/2) - x + O(x^2))
    The test grid for this primitive is x in [0, 1]."""
    xm = mp.mpf(x)
    if xm == 0:
        return mp.mpf(1)
    return (mp.sqrt(mp.pi / 2) - R(xm)) / xm


def _fmt_dict_lines(name: str, mapping: dict) -> list[str]:
    """Emit `name = {x: value, ...}` with each entry on its own line and
    values printed at 18 significant digits (well past double precision)."""
    lines = [f"{name} = {{"]
    for x, v in mapping.items():
        lines.append(f"    {float(x):>4}: {float(v):.17e},")
    lines.append("}")
    return lines


def main(argv):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--write", action="store_true",
                   help="Write tests/_ref_table.py.  Without this, print to stdout.")
    args = p.parse_args(argv)

    # x grids:
    #   - R, R1, R3 (defined on R+): m = 0..40 at step 0.5 (41 nodes, x in [0, 20])
    #   - R_rel (cancellation-free near-zero form): k = 0..20 at step 0.05
    #     (21 nodes, x in [0, 1] -- finer because the valid domain is small)
    xs_full = [0.5  * m for m in range(0, 41)]   # 0, 0.5, 1.0, ..., 20.0
    xs_rel  = [round(0.05 * k, 2) for k in range(0, 21)]   # 0, 0.05, 0.10, ..., 1.0

    R_table     = {x: R(x)     for x in xs_full}
    R1_table    = {x: R1(x)    for x in xs_full}
    R3_table    = {x: R3(x)    for x in xs_full}
    Rrel_table  = {x: R_rel(x) for x in xs_rel}

    header = (
        '"""High-precision reference values for the Mills primitives.\n'
        "\n"
        "Generated by tools/gen_mills_ref.py with mpmath at 50 decimal digits;\n"
        "each value is rounded to 17 significant decimal digits (just past double\n"
        "precision).  Tests import these constants directly so mpmath is not a\n"
        "test-time dependency.  Re-run the generator if the anchor grid changes.\n"
        "\n"
        "Reference definitions:\n"
        "    R(x)       = N(-x)/n(x) = sqrt(pi/2) exp(x^2/2) erfc(x/sqrt(2))\n"
        "    R1(x)      = -R'(x)     = 1 - x R(x)\n"
        "    R3(x)      = -R'''(x)   = (x^2 + 3)(1 - x R(x)) - 1\n"
        "    R_rel(x)   = (sqrt(pi/2) - R(x)) / x,  defined on [0, 1] with R_rel(0) := 1\n"
        "\"\"\"\n"
    )

    lines = [header]
    lines.extend(_fmt_dict_lines("R", R_table))
    lines.append("")
    lines.extend(_fmt_dict_lines("R1", R1_table))
    lines.append("")
    lines.extend(_fmt_dict_lines("R3", R3_table))
    lines.append("")
    lines.extend(_fmt_dict_lines("R_rel", Rrel_table))
    lines.append("")
    out = "\n".join(lines)

    if args.write:
        target = Path(__file__).resolve().parent.parent / "tests" / "_ref_table.py"
        target.write_text(out, encoding="utf-8", newline="\n")
        print(f"wrote {target}  ({len(out)} bytes)")
    else:
        sys.stdout.write(out)


if __name__ == "__main__":
    main(sys.argv[1:])
