# cython: language_level=3, boundscheck=False, wraparound=False, cdivision=True
"""Mills ratio R(x)=N(-x)/n(x) and -R'(x), -R'''(x), plus (sqrt(pi/2)-R(x))/x on [0,1].
Auto-generated by cheby_fit.emit_mathpf -- do not edit.  Coefficient data: _mills_coef.h.
Segmented Chebyshev (flat bucket-major tables) + tiered Laplace continued fraction."""
from libc.math cimport exp, INFINITY
import numpy as np
cimport numpy as np
np.import_array()

cdef extern from "_mills_coef.h":
    const double M_SQRT2PI
    const double M_SQRT2PI_2
    const double U_MAX
    const double X_NEG_MAX
    const double XCF_R[7]
    const double XCF_R1[6]
    const double XCF_R3[5]
    const double N_FRAC_R1
    const int NSEG_R1
    const int TMAX_R1
    const double N_FRAC_R3
    const int NSEG_R3
    const int TMAX_R3
    const double C_Rrel[15]
    const double C_R1[208]
    const double C_R3[405]

# -- C-level scalar kernels (cimport-able: from mathpf.mills cimport _R, _R1, _R3, _R013_CF, _Rrel_below1) --
cdef double _Rrel_below1(double x) noexcept nogil:
    """(sqrt(pi/2) - R(x))/x on [0,1] (deg-14); R = M_SQRT2PI_2 - x*Rrel_below1."""
    cdef const double* c = &C_Rrel[0]
    return ((((((((((((((c[14])*x + c[13])*x + c[12])*x + c[11])*x + c[10])*x + c[9])*x + c[8])*x + c[7])*x + c[6])*x + c[5])*x + c[4])*x + c[3])*x + c[2])*x + c[1])*x + c[0]

cdef double _R013_CF(double x_or_u, int n, int d) noexcept nogil:
    """Shared CF convergent for R / -R' / -R''' at order n in {2,4,6,8,10,12}, d in {0,1,3}.

    Parameter ``x_or_u`` is interpreted polymorphically by ``d`` (u := x^2 + 3 is the
    natural shifted variable of the Mills CF -- see body):

        d = 0:  x_or_u = x          -> R^[n](x)       = N/(x D)         (Mills ratio)
        d = 1:  x_or_u = x*x + 3    -> -R'^[n](x)     = Delta/D         (R1^[n])
        d = 3:  x_or_u = x*x + 3    -> -R'''^[n](x)   = Gamma/D         (R3^[n]; n>=4)

    The d=1 / d=3 paths depend only on u, so accepting u directly skips both the
    ``x*x`` and the ``+ 3.0`` inside the kernel.  This is a true win because the
    d=1/d=3 callers (R1, R3 dispatchers, _R_DD's Taylor branch) need u anyway --
    for the U_MAX overflow guard (where u and x*x differ by 3, negligible at the
    saturation threshold) and for the Taylor descent denominator and ascent
    recurrence (which rewrites cleanly as (u+4), (u+8), (u+12) for r5/r7/r9).
    The d=0 path keeps x because R^[n] has 1/x outside the polynomial.  The
    ``if d == 0`` branches below are compile-time-constant at every call site
    and are dead-code-eliminated.

    Uses the shifted variable u := x^2 + 3 (natural Mills CF structure); evaluates the
    two smaller polynomials Delta(u) (deg n/2-1) and Gamma(u) (deg n/2-2), then recovers
        D = u * Delta - Gamma         (one mult, one sub)
        N = D - Delta                 (pure sub; N = (u-1)*Delta - Gamma = D - Delta)
    Total cost: (n/2-1) + (n/2-2) Horner mults + 1 combine mult = (n-2) mults + 1 div.
    Gamma coefficients have the leading 6 baked in (current line); the un-baked form
    `gamma = 6.0 * (...)` is kept as a comment for traceability.
    """
    cdef double u, delta, gamma, D
    if d == 0:
        u = x_or_u*x_or_u + 3.0                                 # arg is x; form u inside
    else:
        u = x_or_u                                              # arg is already u = x^2 + 3
    if n == 2:                                                  # Delta=1, Gamma=0 (degenerate); D = u, N = u-1
        if d == 0: return (u - 1.0) / (x_or_u * u)              # arg is x
        if d == 1: return 1.0 / u
        return 0.0                                              # -R'''^[2] vanishes
    if n == 4:
        delta = 4.0 + u
        gamma = 6.0                                                                                                  # = 6.0
    elif n == 6:
        delta = 12.0 + u*(12.0 + u)
        gamma = 48.0 + u*6.0                                                                                          # = 6.0*(8.0 + u)
    elif n == 8:
        delta = -24.0 + u*(114.0 + u*(24.0 + u))
        gamma = 324.0 + u*(120.0 + u*6.0)                                                                             # = 6.0*(54.0 + u*(20.0 + u))
    elif n == 10:
        delta = -1248.0 + u*(936.0 + u*(426.0 + u*(40.0 + u)))
        gamma = 1728.0 + u*(1812.0 + u*(216.0 + u*6.0))                                                               # = 6.0*(288.0 + u*(302.0 + u*(36.0 + u)))
    else:  # n == 12
        delta = -22320.0 + u*(4932.0 + u*(6816.0 + u*(1116.0 + u*(60.0 + u))))
        gamma = -1080.0 + u*(24768.0 + u*(5472.0 + u*(336.0 + u*6.0)))                                                # = 6.0*(-180.0 + u*(4128.0 + u*(912.0 + u*(56.0 + u))))
    D = u*delta - gamma                                         # = (x^2+3)*Delta - Gamma
    if d == 1: return delta / D                                 # -R'^[n] = Delta/D
    if d == 3: return gamma / D                                 # -R'''^[n] = Gamma/D
    return (D - delta) / (x_or_u * D)                           # d == 0: R^[n] = N/(xD), N = D - Delta; arg is x

cdef double _R(double x) noexcept nogil:
    """Mills ratio R(x) = N(-x)/n(x); any sign.  Saturates to +inf for x < X_NEG_MAX."""
    cdef double s, d
    cdef int i, o
    cdef const double* c
    if x < 0.0:
        if x < X_NEG_MAX:                                       # exp(x^2/2) overflow -> saturate
            return INFINITY
        return M_SQRT2PI * exp(0.5 * x * x) - _R(-x)
    if x <= 1.0:
        c = &C_Rrel[0]
        return M_SQRT2PI_2 - x * (((((((((((((((c[14])*x + c[13])*x + c[12])*x + c[11])*x + c[10])*x + c[9])*x + c[8])*x + c[7])*x + c[6])*x + c[5])*x + c[4])*x + c[3])*x + c[2])*x + c[1])*x + c[0])
    if x >= XCF_R[0]:                                           # tiered CF via shared R013_CF
        if x >= XCF_R[6]: return 1.0 / x                        # n=0
        if x >= XCF_R[5]: return _R013_CF(x,  2, 0)
        if x >= XCF_R[4]: return _R013_CF(x,  4, 0)
        if x >= XCF_R[3]: return _R013_CF(x,  6, 0)
        if x >= XCF_R[2]: return _R013_CF(x,  8, 0)
        if x >= XCF_R[1]: return _R013_CF(x, 10, 0)
        return            _R013_CF(x, 12, 0)                    # bridge
    d = N_FRAC_R1 + x
    i = <int>(NSEG_R1 * (x - 1.0) / d)
    if i >= TMAX_R1:
        i = TMAX_R1 - 1
    s = ((NSEG_R1 - i) * x - (NSEG_R1 + i * N_FRAC_R1)) / d
    o = i * 8
    c = &C_R1[0]
    return (1.0 - ((((((((c[o + 7])*s + c[o + 6])*s + c[o + 5])*s + c[o + 4])*s + c[o + 3])*s + c[o + 2])*s + c[o + 1])*s + c[o])) / x

cdef double _R1(double x) noexcept nogil:
    """R1(x) = 1 - x R(x) = -R'(x); any sign.  Saturates to +inf for x < X_NEG_MAX."""
    cdef double s, d, u
    cdef int i, o
    cdef const double* c
    if x < 0.0:
        if x < X_NEG_MAX:
            return INFINITY
        return M_SQRT2PI * (-x) * exp(0.5 * x * x) + _R1(-x)
    if x <= 1.0:
        c = &C_Rrel[0]
        return 1.0 - x * (M_SQRT2PI_2 - x * (((((((((((((((c[14])*x + c[13])*x + c[12])*x + c[11])*x + c[10])*x + c[9])*x + c[8])*x + c[7])*x + c[6])*x + c[5])*x + c[4])*x + c[3])*x + c[2])*x + c[1])*x + c[0]))
    if x >= XCF_R1[0]:
        u = x*x + 3.0                                           # kernel's shifted variable; shared with U_MAX guard and _R013_CF
        if u > U_MAX: return 0.0                                # +3 shift in threshold is invisible (U_MAX >> 3 at saturation x ~ 26)
        if x >= XCF_R1[5]: return _R013_CF(u,  2, 1)
        if x >= XCF_R1[4]: return _R013_CF(u,  4, 1)
        if x >= XCF_R1[3]: return _R013_CF(u,  6, 1)
        if x >= XCF_R1[2]: return _R013_CF(u,  8, 1)
        if x >= XCF_R1[1]: return _R013_CF(u, 10, 1)
        return             _R013_CF(u, 12, 1)                   # bridge
    d = N_FRAC_R1 + x
    i = <int>(NSEG_R1 * (x - 1.0) / d)
    if i >= TMAX_R1:
        i = TMAX_R1 - 1
    s = ((NSEG_R1 - i) * x - (NSEG_R1 + i * N_FRAC_R1)) / d
    o = i * 8
    c = &C_R1[0]
    return (((((((c[o + 7])*s + c[o + 6])*s + c[o + 5])*s + c[o + 4])*s + c[o + 3])*s + c[o + 2])*s + c[o + 1])*s + c[o]

cdef double _R3(double x) noexcept nogil:
    """R3(x) = -R'''(x); any sign.  Saturates to +inf for x < X_NEG_MAX."""
    cdef double s, d, u
    cdef int i, o
    cdef const double* c
    if x < 0.0:
        if x < X_NEG_MAX:
            return INFINITY
        return M_SQRT2PI * (-x) * (x*x + 3.0) * exp(0.5 * x * x) + _R3(-x)
    if x >= XCF_R3[0]:
        u = x*x + 3.0                                           # kernel's shifted variable; shared with U_MAX guard and _R013_CF
        if u > U_MAX: return 0.0                                # +3 shift in threshold is invisible (U_MAX >> 3 at saturation)
        if x >= XCF_R3[4]: return _R013_CF(u,  4, 3)
        if x >= XCF_R3[3]: return _R013_CF(u,  6, 3)
        if x >= XCF_R3[2]: return _R013_CF(u,  8, 3)
        if x >= XCF_R3[1]: return _R013_CF(u, 10, 3)
        return             _R013_CF(u, 12, 3)                   # bridge
    d = N_FRAC_R3 + x
    i = <int>(x / d * NSEG_R3)
    s = ((NSEG_R3 - i) * x - i * N_FRAC_R3) / d
    o = i * 9
    c = &C_R3[0]
    return ((((((((c[o + 8])*s + c[o + 7])*s + c[o + 6])*s + c[o + 5])*s + c[o + 4])*s + c[o + 3])*s + c[o + 2])*s + c[o + 1])*s + c[o]

# -- Python-callable numpy-vectorized wrappers --
def millsratio(x):
    """Mills ratio R(x)=N(-x)/n(x); scalar or ndarray, any x."""
    cdef double[::1] f, o
    cdef Py_ssize_t i
    x_arr = np.asarray(x, dtype=np.float64)
    scalar = x_arr.ndim == 0
    flat = np.ascontiguousarray(x_arr.ravel())
    out = np.empty_like(flat)
    f = flat
    o = out
    for i in range(f.shape[0]):
        o[i] = _R(f[i])
    return float(out[0]) if scalar else out.reshape(x_arr.shape)

def millsratio_d1(x):
    """-R'(x) = 1 - x R(x); scalar or ndarray, any x."""
    cdef double[::1] f, o
    cdef Py_ssize_t i
    x_arr = np.asarray(x, dtype=np.float64)
    scalar = x_arr.ndim == 0
    flat = np.ascontiguousarray(x_arr.ravel())
    out = np.empty_like(flat)
    f = flat
    o = out
    for i in range(f.shape[0]):
        o[i] = _R1(f[i])
    return float(out[0]) if scalar else out.reshape(x_arr.shape)

def millsratio_d3(x):
    """-R'''(x); scalar or ndarray, any x."""
    cdef double[::1] f, o
    cdef Py_ssize_t i
    x_arr = np.asarray(x, dtype=np.float64)
    scalar = x_arr.ndim == 0
    flat = np.ascontiguousarray(x_arr.ravel())
    out = np.empty_like(flat)
    f = flat
    o = out
    for i in range(f.shape[0]):
        o[i] = _R3(f[i])
    return float(out[0]) if scalar else out.reshape(x_arr.shape)

def millsratio_rel_below1(x):
    """(sqrt(pi/2)-R(x))/x; scalar or ndarray, 0 <= x <= 1."""
    cdef double[::1] f, o
    cdef Py_ssize_t i
    x_arr = np.asarray(x, dtype=np.float64)
    if np.any((x_arr < 0.0) | (x_arr > 1.0)):
        raise ValueError('millsratio_rel_below1 requires 0 <= x <= 1.')
    scalar = x_arr.ndim == 0
    flat = np.ascontiguousarray(x_arr.ravel())
    out = np.empty_like(flat)
    f = flat
    o = out
    for i in range(f.shape[0]):
        o[i] = _Rrel_below1(f[i])
    return float(out[0]) if scalar else out.reshape(x_arr.shape)

