# cython: language_level=3, boundscheck=False, wraparound=False, cdivision=True
"""Mills ratio R(x)=N(-x)/n(x) and -R'(x), -R'''(x), plus (sqrt(pi/2)-R(x))/x on [0,1].
Auto-generated by cheby_fit.emit_mathpf -- do not edit.  Coefficient data: _mills_coef.h.
Segmented Chebyshev (flat bucket-major tables) + tiered Laplace continued fraction."""
from libc.math cimport exp
import numpy as np
cimport numpy as np
np.import_array()

cdef extern from "_mills_coef.h":
    const double M_SQRT2PI
    const double M_SQRT2PI_2
    const double U_MAX
    const double XCF_R[6]
    const double XCF_R1[5]
    const double XCF_R3[4]
    const double N_FRAC_R1
    const int NSEG_R1
    const int TMAX_R1
    const double N_FRAC_R3
    const int NSEG_R3
    const int TMAX_R3
    const double C_Rrel[15]
    const double C_R1[208]
    const double C_R3[405]

# -- C-level scalar kernels (cimport-able: from mathpf.mills cimport _R, _R1, _R3, _Rrel_below1) --
cdef double _Rrel_below1(double x) noexcept nogil:
    """(sqrt(pi/2) - R(x))/x on [0,1] (deg-14); R = M_SQRT2PI_2 - x*Rrel_below1."""
    cdef const double* c = &C_Rrel[0]
    return ((((((((((((((c[14])*x + c[13])*x + c[12])*x + c[11])*x + c[10])*x + c[9])*x + c[8])*x + c[7])*x + c[6])*x + c[5])*x + c[4])*x + c[3])*x + c[2])*x + c[1])*x + c[0]

cdef double _R(double x) noexcept nogil:
    """Mills ratio R(x) = N(-x)/n(x) (any sign)."""
    cdef double u, s, d
    cdef int i, o
    cdef const double* c
    if x < 0.0:
        return M_SQRT2PI * exp(0.5 * x * x) - _R(-x)
    if x <= 1.0:
        c = &C_Rrel[0]
        return M_SQRT2PI_2 - x * (((((((((((((((c[14])*x + c[13])*x + c[12])*x + c[11])*x + c[10])*x + c[9])*x + c[8])*x + c[7])*x + c[6])*x + c[5])*x + c[4])*x + c[3])*x + c[2])*x + c[1])*x + c[0])
    if x >= XCF_R[0]:
        u = x * x
        if x >= XCF_R[5]:  # n=0 convergent
            return 1.0 / x
        if x >= XCF_R[4]:  # n=2 convergent
            return (2.0 + u) / (x*(3.0 + u))
        if x >= XCF_R[3]:  # n=4 convergent
            return (8.0 + u*(9.0 + u)) / (x*(15.0 + u*(10.0 + u)))
        if x >= XCF_R[2]:  # n=6 convergent
            return (48.0 + u*(87.0 + u*(20.0 + u))) / (x*(105.0 + u*(105.0 + u*(21.0 + u))))
        if x >= XCF_R[1]:  # n=8 convergent
            return (384.0 + u*(975.0 + u*(345.0 + u*(35.0 + u)))) / (x*(945.0 + u*(1260.0 + u*(378.0 + u*(36.0 + u)))))
        return (3840.0 + u*(12645.0 + u*(6090.0 + u*(938.0 + u*(54.0 + u))))) / (x*(10395.0 + u*(17325.0 + u*(6930.0 + u*(990.0 + u*(55.0 + u))))))  # n=10 (bridge)
    d = N_FRAC_R1 + x
    i = <int>(NSEG_R1 * (x - 1.0) / d)
    if i >= TMAX_R1:
        i = TMAX_R1 - 1
    s = ((NSEG_R1 - i) * x - (NSEG_R1 + i * N_FRAC_R1)) / d
    o = i * 8
    c = &C_R1[0]
    return (1.0 - ((((((((c[o + 7])*s + c[o + 6])*s + c[o + 5])*s + c[o + 4])*s + c[o + 3])*s + c[o + 2])*s + c[o + 1])*s + c[o])) / x

cdef double _R1(double x) noexcept nogil:
    """R1(x) = 1 - x R(x) = -R'(x), x >= 0."""
    cdef double u, s, d
    cdef int i, o
    cdef const double* c
    if x <= 1.0:
        c = &C_Rrel[0]
        return 1.0 - x * (M_SQRT2PI_2 - x * (((((((((((((((c[14])*x + c[13])*x + c[12])*x + c[11])*x + c[10])*x + c[9])*x + c[8])*x + c[7])*x + c[6])*x + c[5])*x + c[4])*x + c[3])*x + c[2])*x + c[1])*x + c[0]))
    if x >= XCF_R1[0]:
        u = x * x
        if u > U_MAX:
            return 0.0
        if x >= XCF_R1[4]:  # n=2 convergent
            return 1.0 / (3.0 + u)
        if x >= XCF_R1[3]:  # n=4 convergent
            return (7.0 + u) / (15.0 + u*(10.0 + u))
        if x >= XCF_R1[2]:  # n=6 convergent
            return (57.0 + u*(18.0 + u)) / (105.0 + u*(105.0 + u*(21.0 + u)))
        if x >= XCF_R1[1]:  # n=8 convergent
            return (561.0 + u*(285.0 + u*(33.0 + u))) / (945.0 + u*(1260.0 + u*(378.0 + u*(36.0 + u))))
        return (6555.0 + u*(4680.0 + u*(840.0 + u*(52.0 + u)))) / (10395.0 + u*(17325.0 + u*(6930.0 + u*(990.0 + u*(55.0 + u)))))  # n=10 (bridge)
    d = N_FRAC_R1 + x
    i = <int>(NSEG_R1 * (x - 1.0) / d)
    if i >= TMAX_R1:
        i = TMAX_R1 - 1
    s = ((NSEG_R1 - i) * x - (NSEG_R1 + i * N_FRAC_R1)) / d
    o = i * 8
    c = &C_R1[0]
    return (((((((c[o + 7])*s + c[o + 6])*s + c[o + 5])*s + c[o + 4])*s + c[o + 3])*s + c[o + 2])*s + c[o + 1])*s + c[o]

cdef double _R3(double x) noexcept nogil:
    """R3(x) = -R'''(x), x >= 0."""
    cdef double u, s, d
    cdef int i, o
    cdef const double* c
    if x >= XCF_R3[0]:
        u = x * x
        if u > U_MAX:
            return 0.0
        if x >= XCF_R3[3]:  # n=4 convergent
            return 6.0 / (15.0 + u*(10.0 + u))
        if x >= XCF_R3[2]:  # n=6 convergent
            return 6.0*(11.0 + u) / (105.0 + u*(105.0 + u*(21.0 + u)))
        if x >= XCF_R3[1]:  # n=8 convergent
            return 6.0*(123.0 + u*(26.0 + u)) / (945.0 + u*(1260.0 + u*(378.0 + u*(36.0 + u))))
        return 6.0*(1545.0 + u*(545.0 + u*(45.0 + u))) / (10395.0 + u*(17325.0 + u*(6930.0 + u*(990.0 + u*(55.0 + u)))))  # n=10 (bridge)
    d = N_FRAC_R3 + x
    i = <int>(x / d * NSEG_R3)
    s = ((NSEG_R3 - i) * x - i * N_FRAC_R3) / d
    o = i * 9
    c = &C_R3[0]
    return ((((((((c[o + 8])*s + c[o + 7])*s + c[o + 6])*s + c[o + 5])*s + c[o + 4])*s + c[o + 3])*s + c[o + 2])*s + c[o + 1])*s + c[o]

# -- Python-callable numpy-vectorized wrappers --
def millsratio(x):
    """Mills ratio R(x)=N(-x)/n(x); scalar or ndarray, any x."""
    cdef double[::1] f, o
    cdef Py_ssize_t i
    x_arr = np.asarray(x, dtype=np.float64)
    scalar = x_arr.ndim == 0
    flat = np.ascontiguousarray(x_arr.ravel())
    out = np.empty_like(flat)
    f = flat
    o = out
    for i in range(f.shape[0]):
        o[i] = _R(f[i])
    return float(out[0]) if scalar else out.reshape(x_arr.shape)

def millsratio_d1(x):
    """-R'(x) = 1 - x R(x); scalar or ndarray, x >= 0."""
    cdef double[::1] f, o
    cdef Py_ssize_t i
    x_arr = np.asarray(x, dtype=np.float64)
    if np.any(x_arr < 0.0):
        raise ValueError('millsratio_d1 requires x >= 0.')
    scalar = x_arr.ndim == 0
    flat = np.ascontiguousarray(x_arr.ravel())
    out = np.empty_like(flat)
    f = flat
    o = out
    for i in range(f.shape[0]):
        o[i] = _R1(f[i])
    return float(out[0]) if scalar else out.reshape(x_arr.shape)

def millsratio_d3(x):
    """-R'''(x); scalar or ndarray, x >= 0."""
    cdef double[::1] f, o
    cdef Py_ssize_t i
    x_arr = np.asarray(x, dtype=np.float64)
    if np.any(x_arr < 0.0):
        raise ValueError('millsratio_d3 requires x >= 0.')
    scalar = x_arr.ndim == 0
    flat = np.ascontiguousarray(x_arr.ravel())
    out = np.empty_like(flat)
    f = flat
    o = out
    for i in range(f.shape[0]):
        o[i] = _R3(f[i])
    return float(out[0]) if scalar else out.reshape(x_arr.shape)

def millsratio_rel_below1(x):
    """(sqrt(pi/2)-R(x))/x; scalar or ndarray, 0 <= x <= 1."""
    cdef double[::1] f, o
    cdef Py_ssize_t i
    x_arr = np.asarray(x, dtype=np.float64)
    if np.any((x_arr < 0.0) | (x_arr > 1.0)):
        raise ValueError('millsratio_rel_below1 requires 0 <= x <= 1.')
    scalar = x_arr.ndim == 0
    flat = np.ascontiguousarray(x_arr.ravel())
    out = np.empty_like(flat)
    f = flat
    o = out
    for i in range(f.shape[0]):
        o[i] = _Rrel_below1(f[i])
    return float(out[0]) if scalar else out.reshape(x_arr.shape)

