# Cython header for mathpf.mills -- cimport the scalar kernels, e.g.
#   from mathpf.mills cimport _R, _R1, _R3, _R013_CF, _Rrel_below1
# Auto-generated by cheby_fit.emit_mathpf -- do not edit.
cdef double _R(double x) noexcept nogil
cdef double _R1(double x) noexcept nogil
cdef double _R3(double x) noexcept nogil
cdef double _R013_CF(double x_or_u, int n, int d) noexcept nogil
cdef double _Rrel_below1(double x) noexcept nogil

